#let use_of_ai = [  
= Use of AI in this Paper

As AI, especially Large Language Models (LLMs), are becoming increasingly capable, this paper will leverage this technology. The reason for this approach is that computer scientists and society at large have two options: either ignore AIs' existence and risk falling behind in productivity, code quality, documentation quality, and efficiency, or embrace it to enhance our work where appropriate. We will not use LLMs to directly generate content for this paper. This decision stands even though—through simple obfuscations—it is impossible to detect or verify if this work contains artificially generated content. The primary use of AI in this paper will be for correcting spelling and grammatical errors, as well as having LLMs suggest alternative phrasings to improve readability and comprehension. These suggestions will be used to refine our writing, ensuring clarity and coherence throughout the document. Tools used to archive this: @google2025aistudio @openai2025api @anthropic2025claude @grammarly2025editor While it may not be required to include this type of information in a project, it is crucial to establish a standard practice of declaring the use of generative tools in any written work. Therefore, despite the option to omit this paragraph, we have chosen to include it in the interest of transparency and honesty regarding the use of generative AI in this work.

As artificial intelligence, particularly Large Language Models (LLMs), continues to advance in capability, this paper acknowledges and strategically incorporates this technology. Computer scientists and society face two distinct options: either disregard AI's existence—potentially sacrificing productivity, code quality, documentation standards, and operational efficiency—or judiciously embrace it to enhance research methodologies where appropriate.\
This work does not utilize LLMs for direct content generation. This principled stance remains despite the recognition that—through various obfuscation techniques—artificially generated content has become increasingly difficult to detect or verify. Instead, AI serves an auxiliary function in this paper, primarily for identifying and correcting linguistic errors and suggesting alternative phrasings to enhance readability and comprehension. These suggestions have been selectively implemented to refine our writing, ensuring optimal clarity and coherence throughout the document.\
The specific tools employed include: @google2025aistudio, @openai2025api, @anthropic2025claude, and @grammarly2025editor. While disclosure of such technological assistance may not be formally required in academic publishing standards, we consider it essential to establish transparent practices regarding the utilization of generative tools in scholarly work. Therefore, despite the option to omit this information, we have included this statement to maintain intellectual integrity and transparency regarding the integration of generative AI in this research.



]