#let acronyms = (
  AI: "Artificial Intelligence",
  AGI: "Artificial General Intelligence",
  API: "Application Programming Interface",
  ARC: "Abstraction and Reasoning Corpus",
  CoT: "Chain-of-Thought",
  CPU: "Central Processing Unit",
  CUDA: "Compute Unified Device Architecture",
  DFS: "Depth-First Search",
  DRL: "Deep Reinforcement Learning",
  DSL: "Domain-Specific Language",
  FSDP: "Fully Sharded Data Parallel",
  GPU: "Graphics Processing Unit",
  JSON: "JavaScript Object Notation",
  JSONL: "JSON Lines",
  KV: "Key-Value", // Contextually often Key-Value Cache
  LLM: "Large Language Model",
  ML: "Machine Learning",
  MORLAIF: "Multi-Objective Reinforcement Learning from AI Feedback",
  OOM: "Out Of Memory",
  ORM: "Outcome Reward Model",
  PRM: "Process Reward Model",
  RL: "Reinforcement Learning",
  VRAM: "Video Random Access Memory",
  PPO: "Proximal Policy Optimization",
)